### ISSUE TITLE
Error when sending xtz from an unrevealed account.

### ISSUE THREAD

**Issue by baahkusi** [Tezsure/Tezster_dart#12] opened 2021-01-26 09:58 UTC
This error is raised `proto.007-PsDELPH1.contract.unrevealed_key` when you try to send xtz from an unrevealed account. I can see from code the reveal operation is prepended as required. However it seems the fees attached for revelation in code is 0 instead of 0.275 xtz. This could be why I'm getting this error, but I'm not sure.

**Comment by aditya-tezsure** [comment] 2021-01-29 12:06
@baahkusi was the account activated and not revealed ?

**Comment by baahkusi** [comment] 2021-01-29 12:55
> @baahkusi was the account activated and not revealed ?

`tz1cuc6hnfgCpgUkLYELjLicYWSmjM1uoGrQ` is the account on both mainnet and testnet. Activation is only neccessary for fundraiser accounts.

**Comment by aditya-tezsure** [comment] 2021-02-01 09:51
@baahkusi I believe multiple operations on the same block id via the same account is not possible hence we await operation confirmation for the previous operation before pushing in the next operation in the block. Also, If the issue isn't this maybe we can have a clear picture if you could share some details like the operation id of the transaction where exactly you faced an issue.

**Comment by aditya-tezsure** [comment] 2021-02-01 09:53
Also, you can use our telegram link to follow quick actions on bug fixes
[https://t.me/tezster](https://t.me/tezster)

**Comment by baahkusi** [comment] 2021-02-01 14:08
> @baahkusi I believe multiple operations on the same block id via the same account is not possible hence we await operation confirmation for the previous operation before pushing in the next operation in the block. Also, If the issue isn't this maybe we can have a clear picture if you could share some details like the operation id of the transaction where exactly you faced an issue.

Basically, the `sendTransactionOperation` does not work if the sending account is not revealed already revealed. With regards to the revelation operation, the `public_key` value is also needed. It seems the operation model only caters for transaction and delegation operations.
https://github.com/Tezsure/Tezster_dart/blob/1ec9b772b1cd30ea17b218de6032db9110b3c6ae/lib/models/operation_model.dart#L33

**Comment by yoyodefi** [comment] 2021-02-18 08:42
@baahkusi let us know if it works and we can close this issue.

**Comment by baahkusi** [comment] 2021-02-19 14:39
> @baahkusi let us know if it works and we can close this issue.

Hi @malviyaop I still get the same error.

```
Exception (Exception: Status code ==> 200
Response ==> [{kind: branch, id: proto.008-PtEdo2Zk.contract.unrevealed_key, contract: tz1Mrfe5RQu4i1aRnpYj3ApmbZLyNy6YFxjk}] 
 Error ==> branch : proto.008-PtEdo2Zk.contract.unrevealed_key, )
```

Here is my code.

```
static Future<Map> transfer(Map coin, Map output, [bool dryRun = true]) async {
    var server = 'https://mainnet.smartpy.io';
    var keyStore = KeyStoreModel(
      publicKey: coin['publicKey'],
      secretKey: coin['privateKey'],
      publicKeyHash: coin['publicKeyHash'],
    );
    var signer = await TezsterDart.createSigner(TezsterDart.writeKeyWithHint(keyStore.secretKey, 'edsk'));

    try {
      var result = await TezsterDart.sendTransactionOperation(
        server,
        signer,
        keyStore,
        output['address'],
        output['amount'],
        output['fee'],
      );
      print(result);
      return {'status': true, 'coinType': TEZOS};
    } catch (e) {
      return {'status': false, 'coinType': TEZOS};
    }
}
```

**Comment by baahkusi** [comment] 2021-02-19 15:56
Just wanted to add that if the account is already revealed then the send function works correctly. I tested this by revealing a newly created account elsewhere and using the library to send.

**Closed as completed** 2021-02-23 12:33 UTC
Labels: bug
